### PR TITLE
Problems Related to the book Introduction to MATLAB for Engineers

### PR DESCRIPTION
**Pull request by QuantumNovice**

### CODE REVIEW

**Comment by cozek** [comment]
I think we should remain generalized and not make a category based on a book. Thoughts @AnupKumarPanwar ?

**Comment by QuantumNovice** [comment]
I've solved question from the book mentioned in this code. That's why I referred to the book. May be I can refer  to the book in comments  and remove the directory structure.

**Comment by cozek** [comment]
Hi. I appreciate your contribution. And I think it's valuable for the repo.
I just think that it might be better if we orient to a generalized
structure.

**Comment by QuantumNovice** [comment]
Hey, so I got rid of that structure.

**Pull request merged**
