### PR TITLE
Minimization optimization Genetic algorithm

### PR DESCRIPTION
**Pull request by Abhishek-photon**
This is a minimization code for a polynomial function using binary coded Genetic algorithm

### CODE REVIEW

**Comment by cozek** [comment]
Since this is an application of GA, please rename the `Minimization` folder to a more appropriate name.
Perhaps like 'Minimization of Polynomial Function' or whatever is more appropriate. Also, please add it the readme under a new category Genetic Algorithm.

Everything else seems fine. 
Thanks for your contribution.

**Comment by Abhishek-photon** [comment]
Sir,
I will do as instructed by you .

**Comment by Abhishek-photon** [comment]
sir,
please check  I have done it from here.

>

**Comment by Abhishek-photon** [comment]
sir this PR is for hacktober . I request you to please add label to my PR as it has been merged.

**Comment by Abhishek-photon** [comment]
thank you sir.
Sir I have applied real coded GA in one of the PR...please review it too.
Thank you.

**Pull request merged**
