### PR TITLE
Create linear_diophantine_eqn.m

### PR DESCRIPTION
**Pull request by KaushalDevrari**

### CODE REVIEW

**Comment by KaushalDevrari** [comment]
sir,
could you add the hacktoberfest-accepted on it.

**Comment by KaushalDevrari** [comment]
could you add the hacktoberfest-accepted label to this merged pr.

**Comment by KaushalDevrari** [comment]
Sir in the hacktoberfest this repo is showing invalid so please add the hactoberfest accepted label on it

**Comment by cozek** [comment]
Sure. I will do it when I get time.

**Pull request merged**
